pipeline {
    agent {
        label 'builder' // 在整个 Pipeline 中使用同一个 Docker agent
    }
    stages {
        stage('环境检查') {
            steps {
                script {
                    echo 'Checking environment on the same agent...'
                    sh 'java -version'
                    sh 'go version'
                    sh 'git --version'
                }
            }
        }
        stage('拉取代码') {
            steps {
                script {
                    echo 'Pulling code on the same agent...'
                    sh 'git clone --depth 1 https://github.com/kangjiantsui/go-file-upload.git'
                    sh 'ls -la go-file-upload'
                    sh 'cat go-file-upload/README.md'
                }
            }
        }
    }
}
