pipeline {
    agent {
        label 'builder'
    }
    stages {
        stage('环境检查') {
            steps {
                script {
                    echo 'Checking environment on the same agent...'
                    sh 'java -version'
                    sh 'go version'
                    sh 'git --version'
                    sh 'docker version' // 检查 Docker 版本
                }
            }
        }
        stage('拉取代码') {
            steps {
                script {
                    echo 'Pulling code on the same agent...'
                    sh 'git clone --depth 1 https://github.com/kangjiantsui/go-file-upload.git'
                    sh 'ls -la go-file-upload'
                    sh 'cat go-file-upload/README.md'
                }
            }
        }
        stage('构建镜像') {
            steps {
                script {
                    echo 'Building Docker image...'
                    sh 'cd go-file-upload'
                    sh './build_image.sh'
                }
            }
        }
    }
}
