pipeline {
    agent {
        label 'builder'
    }
    stages {
        stage('环境检查') {
            steps {
                script {
                    echo 'Checking environment on the same agent...'
                    sh 'java -version'
                    sh 'go version'
                    sh 'git --version'
                    sh 'docker version'
                    sh 'cat ~/.ssh/id_ed25519.pub'
                }
            }
        }
        stage('拉取代码') {
            steps {
                script {
                    echo 'Pulling code on the same agent...'
                    sh 'git clone --depth 1 git@github.com:kangjiantsui/go-file-upload.git'
                    sh 'ls -la go-file-upload'
                    sh 'cat go-file-upload/README.md'
                }
            }
        }
        stage('构建镜像') {
            steps {
                script {
                    echo 'Building Docker image...'
                    sh '''
                        chmod -R 777 go-file-upload
                        cd go-file-upload
                        ls -la
                        ./build_image.sh
                    '''
                }
            }
        }
    }
}
